In [6]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.datasets import load_boston
from sklearn.ensemble import AdaBoostRegressor

In [7]:
# 加载数据
data = load_boston()
print(data.data, data.target)

[[6.3200e-03 1.8000e+01 2.3100e+00 ... 1.5300e+01 3.9690e+02 4.9800e+00]
 [2.7310e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9690e+02 9.1400e+00]
 [2.7290e-02 0.0000e+00 7.0700e+00 ... 1.7800e+01 3.9283e+02 4.0300e+00]
 ...
 [6.0760e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 5.6400e+00]
 [1.0959e-01 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9345e+02 6.4800e+00]
 [4.7410e-02 0.0000e+00 1.1930e+01 ... 2.1000e+01 3.9690e+02 7.8800e+00]] [24.  21.6 34.7 33.4 36.2 28.7 22.9 27.1 16.5 18.9 15.  18.9 21.7 20.4
 18.2 19.9 23.1 17.5 20.2 18.2 13.6 19.6 15.2 14.5 15.6 13.9 16.6 14.8
 18.4 21.  12.7 14.5 13.2 13.1 13.5 18.9 20.  21.  24.7 30.8 34.9 26.6
 25.3 24.7 21.2 19.3 20.  16.6 14.4 19.4 19.7 20.5 25.  23.4 18.9 35.4
 24.7 31.6 23.3 19.6 18.7 16.  22.2 25.  33.  23.5 19.4 22.  17.4 20.9
 24.2 21.7 22.8 23.4 24.1 21.4 20.  20.8 21.2 20.3 28.  23.9 24.8 22.9
 23.9 26.6 22.5 22.2 23.6 28.7 22.6 22.  22.9 25.  20.6 28.4 21.4 38.7
 43.8 33.2 27.5 26.5 18.6 19.3 20.1 19.5 19.5 20.4 19.8 19.

/Users/admin/Workspace/DataDev/venv/lib/python3.10/site-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np

        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the Califor

In [8]:
# 分割数据
train_x, test_x, train_y, test_y = train_test_split(data.data, data.target, test_size=0.25, random_state=33)

In [9]:
# 使用 AdaBoost 回归模型
regressor = AdaBoostRegressor()
regressor.fit(train_x, train_y)
pred_y = regressor.predict(test_x)
mse = mean_squared_error(test_y, pred_y)
print('房价预测结果：', pred_y)
print('均方误差：', round(mse, 2))

房价预测结果： [19.0483871  11.22222222 13.15294118 17.43264249 24.4232     22.1862069
 29.40128205 17.84130435 29.91071429 18.32037037 29.40128205 33.25833333
 11.35555556 24.4232     13.12222222 24.83703704 17.30350877 16.9
 29.37192982 24.63203883 17.43264249 17.84130435 17.66666667 18.32037037
 32.63552632 17.57837838 22.19459459 24.83703704 11.54189189 31.48709677
 17.43264249 25.37014218 11.22222222 21.08135593 26.66666667 31.48709677
 25.37014218 11.54189189 13.47878788 25.34966887 13.18292683 12.72906977
 32.63552632 17.57837838 26.88555556 19.46578947 17.84130435 19.44719101
 25.37014218 20.29756098 17.30350877 33.54470588 15.29259259 17.30350877
 24.92589928 21.08135593 24.4232     16.9637931  24.28844221 21.95837104
 18.4        15.62727273 44.73888889 21.25108696 16.9637931  25.72396694
 25.34966887 11.54189189 18.24516129 29.37192982 22.75714286 18.32037037
 17.57837838 26.88555556 19.96728972 46.89444444 15.3296875  11.35555556
 16.89927007 24.28844221 20.30535714 13.18292683 11

In [10]:
from sklearn.tree import DecisionTreeRegressor

# 使用决策树回归模型
dec_regressor = DecisionTreeRegressor()
dec_regressor.fit(train_x, train_y)
pred_y = dec_regressor.predict(test_x)
mse = mean_squared_error(test_y, pred_y)
print('决策树均方误差：', round(mse, 2))

决策树均方误差： 35.79


In [11]:
from sklearn.neighbors import KNeighborsRegressor

knn_regressor = KNeighborsRegressor()
knn_regressor.fit(train_x, train_y)
pred_y = knn_regressor.predict(test_x)
mse = mean_squared_error(test_y, pred_y)
print('KNN 均方误差：', round(mse, 2))

KNN 均方误差： 27.87


In [36]:
# AdaBoost 与决策树模型的比较
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
from sklearn.metrics import zero_one_loss
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import AdaBoostClassifier

In [37]:
# 设置 AdaBoost 迭代次数
n_estimators = 200
X, y = datasets.make_hastie_10_2(n_samples=12000, random_state=1)
# 从 12000 个数据中取前 2000 行作为测试集、其余作为训练集
train_x, train_y = X[:2000], y[:2000]
test_x, text_y = X[2000:], y[2000:]
print(test_x, test_y)

[[-1.93156389 -0.16042612 -0.83221954 ... -0.11040249 -0.60073243
   1.13414588]
 [-1.1072485   0.88625506 -0.03557352 ...  1.03615635  0.51788873
   1.08449476]
 [-0.09772724 -0.49127897  0.42154907 ...  1.62140268 -0.64834049
   1.0642546 ]
 ...
 [-0.93116013 -1.66204029  0.30451552 ... -0.13420095  0.29183149
  -0.43300684]
 [-1.3787448   0.83384136 -1.53900483 ...  0.89981334 -1.44271785
   2.51028547]
 [ 0.82776805  2.04855517  2.77822335 ...  0.12579842 -0.1916412
   0.67553921]] [20.5  5.6 13.4 12.6 21.2 19.7 32.4 14.8 33.  21.4 30.1 36.   8.4 21.6
 16.3 23.  14.9 14.1 31.1 11.9 12.7 27.9 20.8 19.6 32.  21.9 23.2 23.8
 10.8 34.9 19.1 26.5 10.5 17.5 24.  36.1 25.3 13.8 27.5 24.6 12.7  9.5
 32.7 13.8 23.5 17.7 15.6 22.5 26.2 20.6 14.1 33.3 15.2 14.9 21.6 17.2
 23.1 11.7 20.6 22.2 23.1 18.4 43.8 21.1 14.9 28.7 23.3 13.8 19.7 30.5
 19.  19.1 19.  26.6 17.5 21.9 13.8  8.8 19.4 28.1 21.  11.8  7.2 24.1
 20.  18.9 50.  13.3 50.  41.3 28.7 19.9 16.5 10.9 13.4 32.9 20.6 25.
 19.5 19.9 15

In [39]:
# 弱分类器
dt_stump = DecisionTreeClassifier(max_depth=1,min_samples_leaf=1)
dt_stump.fit(train_x, train_y)
dt_stump_err = 1.0 - dt_stump.score(test_x, test_y)

ValueError: Found input variables with inconsistent numbers of samples: [127, 10000]

In [26]:
# 决策树分类器
dt = DecisionTreeClassifier()
dt.fit(train_x, train_y)
dt_err = 1.0-dt.score(test_x, test_y)

ValueError: Found input variables with inconsistent numbers of samples: [127, 2000]

In [31]:
# AdaBoost 分类器
ada = AdaBoostClassifier(base_estimator=dt_stump, n_estimators=n_estimators)
ada.fit(train_x, train_y)

AdaBoostClassifier(base_estimator=DecisionTreeClassifier(max_depth=1),
                   n_estimators=200)

In [ ]:
# 三个分类器的错误率可视化
fig = plt.figure()
# 设置 plt 正确显示中文
plt.rcParams['font.sans-serif'] = ['SimHei']
ax = fig.add_subplot(111)
ax.plot([1, n_estimators], [dt_stump_err]*2, 'k-', label=u'决策树弱分类器 错误率')
ax.plot([1, n_estimators], [dt_err]*2, 'k--', label=u'决策树模型 错误率')
ada_err = np.zeros((n_estimators,))
# 遍历每次迭代的结果、i 为迭代次数、pred_y 为预测结果
for i, pred_y in enumerate(ada.staged_predict(test_x)):
    # 统计错误率
    ada_err[i] = zero_one_loss(pred_y, test_y)
# 绘制每次迭代的 AdaBoost 错误率
ax.plot(np.arange(n_estimators)+1, ada_err, label='AdaBoost Test 错误率', color='orange')
ax.set_xlable('迭代次数')
ax.set_ylabel('错误率')
leg = ax.legend(loc='upper right', fancybox=True)
plt.show()